/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Analytics: () => import('#controllers/analytics_controller'),
  Tools: () => import('#controllers/tools_controller'),
}
