/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccessRequestSchema extends BaseModel {
  static $columns = ['businessJustification', 'id', 'processedAt', 'processedBy', 'processingNotes', 'requestedAt', 'status', 'toolId', 'userId'] as const
  $columns = AccessRequestSchema.$columns
  @column()
  declare businessJustification: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare processedAt: DateTime | null
  @column()
  declare processedBy: number | null
  @column()
  declare processingNotes: string | null
  @column.dateTime()
  declare requestedAt: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare toolId: number
  @column()
  declare userId: number
}

export class CategorySchema extends BaseModel {
  static $columns = ['colorHex', 'createdAt', 'description', 'id', 'name'] as const
  $columns = CategorySchema.$columns
  @column()
  declare colorHex: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
}

export class CostTrackingSchema extends BaseModel {
  static $columns = ['activeUsersCount', 'createdAt', 'id', 'monthYear', 'toolId', 'totalMonthlyCost'] as const
  $columns = CostTrackingSchema.$columns
  @column()
  declare activeUsersCount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare monthYear: DateTime
  @column()
  declare toolId: number
  @column()
  declare totalMonthlyCost: string
}

export class ToolSchema extends BaseModel {
  static $columns = ['activeUsersCount', 'categoryId', 'createdAt', 'description', 'id', 'monthlyCost', 'name', 'ownerDepartment', 'status', 'updatedAt', 'vendor', 'websiteUrl'] as const
  $columns = ToolSchema.$columns
  @column()
  declare activeUsersCount: number
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare monthlyCost: string
  @column()
  declare name: string
  @column()
  declare ownerDepartment: string
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vendor: string | null
  @column()
  declare websiteUrl: string | null
}

export class UsageLogSchema extends BaseModel {
  static $columns = ['actionsCount', 'createdAt', 'id', 'sessionDate', 'toolId', 'usageMinutes', 'userId'] as const
  $columns = UsageLogSchema.$columns
  @column()
  declare actionsCount: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare sessionDate: DateTime
  @column()
  declare toolId: number
  @column()
  declare usageMinutes: number | null
  @column()
  declare userId: number
}

export class UserToolAccessSchema extends BaseModel {
  static $columns = ['grantedAt', 'grantedBy', 'id', 'revokedAt', 'revokedBy', 'status', 'toolId', 'userId'] as const
  $columns = UserToolAccessSchema.$columns
  @column.dateTime()
  declare grantedAt: DateTime | null
  @column()
  declare grantedBy: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare revokedBy: number | null
  @column()
  declare status: string | null
  @column()
  declare toolId: number
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'department', 'email', 'hireDate', 'id', 'name', 'role', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare department: string
  @column()
  declare email: string
  @column.date()
  declare hireDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare role: string | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
