import type { Tool } from '../types';

export const mockTools: Tool[] = [
  {
    id: 1,
    name: 'Slack',
    description: 'Team messaging and collaboration platform',
    vendor: 'Slack Technologies',
    website_url: 'https://slack.com',
    category: 'Communication',
    monthly_cost: 8,
    owner_department: 'Engineering',
    status: 'active',
    active_users_count: 245,
    created_at: '2026-05-18T07:24:55.000Z',
  },
  {
    id: 2,
    name: 'Figma',
    description: 'Collaborative design and prototyping',
    vendor: 'Figma Inc.',
    website_url: 'https://figma.com',
    category: 'Design',
    monthly_cost: 15,
    owner_department: 'Design',
    status: 'active',
    active_users_count: 32,
    created_at: '2026-05-18T07:24:55.000Z',
  },
  {
    id: 3,
    name: 'GitHub',
    description: 'Version control and collaboration',
    vendor: 'GitHub Inc.',
    website_url: 'https://github.com',
    category: 'Development',
    monthly_cost: 21,
    owner_department: 'Engineering',
    status: 'active',
    active_users_count: 89,
    created_at: '2026-05-18T07:24:55.000Z',
  },
  {
    id: 4,
    name: 'Notion',
    description: 'All-in-one workspace',
    vendor: 'Notion Labs Inc.',
    website_url: 'https://notion.so',
    category: 'Productivity',
    monthly_cost: 8,
    owner_department: 'Operations',
    status: 'trial',
    active_users_count: 156,
    created_at: '2026-05-18T07:24:55.000Z',
  },
  {
    id: 5,
    name: 'Adobe CC',
    description: 'Creative cloud suite',
    vendor: 'Adobe',
    website_url: 'https://adobe.com',
    category: 'Design',
    monthly_cost: 60,
    owner_department: 'Marketing',
    status: 'deprecated',
    active_users_count: 12,
    created_at: '2026-05-18T07:24:55.000Z',
  },
  {
    id: 6,
    name: 'Zoom',
    description: 'Video conferencing',
    vendor: 'Zoom Video Communications',
    website_url: 'https://zoom.us',
    category: 'Communication',
    monthly_cost: 14.99,
    owner_department: 'Operations',
    status: 'active',
    active_users_count: 198,
    created_at: '2026-05-18T07:24:55.000Z',
  },
  {
    id: 7,
    name: 'Jira',
    description: 'Project management and issue tracking',
    vendor: 'Atlassian',
    website_url: 'https://jira.atlassian.com',
    category: 'Development',
    monthly_cost: 7.5,
    owner_department: 'Engineering',
    status: 'trial',
    active_users_count: 67,
    created_at: '2026-05-18T07:24:55.000Z',
  },
  {
    id: 8,
    name: 'Salesforce',
    description: 'CRM and sales platform',
    vendor: 'Salesforce',
    website_url: 'https://salesforce.com',
    category: 'Marketing',
    monthly_cost: 150,
    owner_department: 'Sales',
    status: 'active',
    active_users_count: 45,
    created_at: '2026-05-18T07:24:55.000Z',
  },
];

export const mockKpis = {
  monthlyBudget: {
    label: 'Monthly Budget',
    value: '€28,750',
    target: '€30k',
    change: '+12%',
    icon: 'budget' as const,
  },
  activeTools: {
    label: 'Active Tools',
    value: 147,
    change: '+8',
    icon: 'tools' as const,
  },
  departments: {
    label: 'Departments',
    value: 8,
    change: '+2',
    icon: 'departments' as const,
  },
  costPerUser: {
    label: 'Cost Per User',
    value: '€156',
    change: '€-12',
    icon: 'cost' as const,
  },
};
